name: Deploy React App to Firebase Hosting

on:
  push:
    branches:
      - master  # or 'main' if your branch name is 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or match your React version

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccountToken: '${{ secrets.FIREBASE_TOKEN }}'
          channelId: live
          projectId: frontend-firebase19

